"""add per-user quota columns

Revision ID: a7beeba57ba6
Revises: 2bfd649f8588
Create Date: 2026-08-10 22:09:13.539977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7beeba57ba6'
down_revision: Union[str, Sequence[str], None] = '2bfd649f8588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_environments', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cpu_limit', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('mem_limit_mb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mem_limit_mb')
    op.drop_column('users', 'cpu_limit')
    op.drop_column('users', 'max_environments')
    # ### end Alembic commands ###
